import { useEffect, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { apiFetch } from '../lib/api.js';

export default function Analytics() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { apiFetch('/api/analytics').then(async (res) => { const body = await res.json(); if (!res.ok) throw new Error(body.message); return body; }).then(setData).catch((err) => setError(err.message || 'Unable to load analytics.')); }, []);
  const kpis = data?.kpis;
  return <div><h1 className="text-xl font-semibold text-white">Reports &amp; Analytics</h1><p className="mt-1 text-sm text-gray-400">Financial and utilization performance from your operational records.</p>{error && <div className="mt-4 rounded-md border border-status-red/40 bg-status-red/10 px-3 py-2 text-sm text-status-red">{error}</div>}
    <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Fuel Efficiency" value={kpis ? `${Number(kpis.fuelEfficiency).toFixed(2)} km/l` : '—'} color="#22c55e" /><Kpi label="Fleet Utilization" value={kpis ? `${Number(kpis.fleetUtilization).toFixed(1)}%` : '—'} color="#3b82f6" /><Kpi label="Operational Cost" value={kpis ? money(kpis.operationalCost) : '—'} color="#f97316" /><Kpi label="Vehicle ROI" value={kpis ? `${Number(kpis.roi).toFixed(2)}%` : '—'} color="#d97706" detail="ROI = (Revenue - (Maintenance + Fuel)) / Acquisition Cost" /></div>
    <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-2"><ChartPanel title="Monthly Revenue"><ResponsiveContainer width="100%" height={280}><BarChart data={data?.monthlyRevenue || []}><CartesianGrid stroke="#2a2a2a" vertical={false}/><XAxis dataKey="month" stroke="#9ca3af" fontSize={12}/><YAxis stroke="#9ca3af" fontSize={12} tickFormatter={(v) => `₹${Number(v)/1000}k`}/><Tooltip contentStyle={{ background: '#141414', border: '1px solid #2a2a2a' }} formatter={(v) => money(v)}/><Bar dataKey="revenue" fill="#d97706" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></ChartPanel><ChartPanel title="Top Costliest Vehicles"><ResponsiveContainer width="100%" height={280}><BarChart data={data?.costliestVehicles || []} layout="vertical" margin={{ left: 16 }}><CartesianGrid stroke="#2a2a2a" horizontal={false}/><XAxis type="number" stroke="#9ca3af" fontSize={12} tickFormatter={(v) => `₹${Number(v)/1000}k`}/><YAxis dataKey="regNo" type="category" stroke="#9ca3af" fontSize={12}/><Tooltip contentStyle={{ background: '#141414', border: '1px solid #2a2a2a' }} formatter={(v) => money(v)}/><Bar dataKey="cost" radius={[0,4,4,0]}>{(data?.costliestVehicles || []).map((_, index) => <Cell key={index} fill={index === 0 ? '#ec4899' : index === 1 ? '#f97316' : '#3b82f6'} />)}</Bar></BarChart></ResponsiveContainer></ChartPanel></div>
  </div>;
}
function Kpi({ label, value, color, detail }) { return <div className="panel p-4" style={{ borderLeft: `3px solid ${color}` }}><p className="text-xs font-medium text-gray-400">{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p>{detail && <p className="mt-2 text-xs leading-relaxed text-gray-500">{detail}</p>}</div>; }
function ChartPanel({ title, children }) { return <section className="panel p-5"><h2 className="text-sm font-semibold text-white">{title}</h2><div className="mt-4">{children}</div></section>; }
function money(value) { return `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`; }
