import { useEffect, useState } from 'react';
import StatusBadge from '../components/StatusBadge.jsx';
import { apiFetch } from '../lib/api.js';

export default function Fleet() {
  const [vehicles, setVehicles] = useState([]); const [error, setError] = useState('');
  useEffect(() => { apiFetch('/api/vehicles').then(async (res) => { const body = await res.json(); if (!res.ok) throw new Error(body.message); return body; }).then(setVehicles).catch((err) => setError(err.message || 'Unable to load vehicle registry.')); }, []);
  return <div><h1 className="text-xl font-semibold text-white">Vehicle Registry</h1><p className="mt-1 text-sm text-gray-400">Live fleet capacity, odometer, and dispatch status.</p>{error && <div className="mt-4 rounded-md border border-status-red/40 bg-status-red/10 px-3 py-2 text-sm text-status-red">{error}</div>}<div className="panel mt-6 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-base-border text-xs uppercase tracking-wide text-gray-500">{['Reg. No.','Name / Model','Type','Capacity','Odometer','Acq. Cost','Status','Region'].map((head) => <th className="p-4" key={head}>{head}</th>)}</tr></thead><tbody>{vehicles.map((vehicle) => <tr key={vehicle.id} className="border-b border-base-border/60 last:border-0"><td className="p-4 font-medium text-white">{vehicle.regNo}</td><td className="p-4 text-gray-300">{vehicle.name}</td><td className="p-4 text-gray-300">{vehicle.type}</td><td className="p-4 text-gray-300">{Number(vehicle.maxCapacityKg).toLocaleString('en-IN')} kg</td><td className="p-4 text-gray-300">{Number(vehicle.odometer).toLocaleString('en-IN')} km</td><td className="p-4 text-gray-300">₹{Number(vehicle.acquisitionCost).toLocaleString('en-IN')}</td><td className="p-4"><StatusBadge status={vehicle.status}/></td><td className="p-4 text-gray-400">{vehicle.region || '—'}</td></tr>)}{!vehicles.length && <tr><td colSpan="8" className="p-8 text-center text-gray-500">Loading vehicles...</td></tr>}</tbody></table></div><p className="mt-4 rounded-md border border-base-border bg-base-panel px-3 py-2 text-sm text-gray-400">Rule: Retired/In Shop vehicles are hidden from Trip Dispatcher.</p></div>;
}
