import { useEffect, useState } from 'react';
import StatusBadge from '../components/StatusBadge.jsx';
import { apiFetch } from '../lib/api.js';
const today = new Date().toISOString().slice(0, 10);
const FUEL_EMPTY = { vehicleId: '', logDate: today, liters: '', cost: '' };
const EXPENSE_EMPTY = { vehicleId: '', tripId: '', maintenanceId: '', toll: '0', other: '0' };

export default function FuelExpenses() {
  const [options, setOptions] = useState({ vehicles: [], trips: [], maintenance: [] }); const [fuel, setFuel] = useState([]); const [expenses, setExpenses] = useState([]); const [summary, setSummary] = useState({ totalOperationalCost: 0 }); const [filter, setFilter] = useState(''); const [modal, setModal] = useState(''); const [form, setForm] = useState(FUEL_EMPTY); const [errors, setErrors] = useState({}); const [message, setMessage] = useState('');
  const load = async () => { try { const suffix = filter ? `?vehicleId=${filter}` : ''; const [o,f,e,s] = await Promise.all([apiFetch('/api/finance/options'), apiFetch(`/api/finance/fuel-logs${suffix}`), apiFetch(`/api/finance/expenses${suffix}`), apiFetch(`/api/finance/summary${suffix}`)]); const [od,fd,ed,sd] = await Promise.all([o.json(),f.json(),e.json(),s.json()]); if (![o,f,e,s].every((r) => r.ok)) throw new Error('Unable to load financial data.'); setOptions(od); setFuel(fd); setExpenses(ed); setSummary(sd); } catch (err) { setMessage(err.message); } };
  useEffect(() => { load(); }, [filter]);
  const open = (kind) => { setModal(kind); setErrors({}); setForm(kind === 'fuel' ? FUEL_EMPTY : EXPENSE_EMPTY); };
  const setField = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const save = async (event) => { event.preventDefault(); setErrors({}); const endpoint = modal === 'fuel' ? '/api/finance/fuel-logs' : '/api/finance/expenses'; try { const response = await apiFetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { if (data.field) setErrors({ [data.field]: data.message }); else setMessage(data.message); return; } setModal(''); setMessage(modal === 'fuel' ? 'Fuel log saved.' : 'Expense saved.'); await load(); } catch { setMessage('Unable to save record. Please try again.'); } };
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-xl font-semibold text-white">Fuel &amp; Expense Management</h1><p className="mt-1 text-sm text-gray-400">Track fuel, toll, and operational costs from live records.</p></div><select className="input-field" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">All vehicles</option>{options.vehicles.map((v) => <option key={v.id} value={v.id}>{v.regNo}</option>)}</select></div>{message && <div className="mt-4 rounded-md border border-accent/40 bg-accent/10 px-3 py-2 text-sm text-gray-200">{message}</div>}
    <section className="panel mt-6 overflow-x-auto p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Fuel Logs</h2><button className="btn-primary" onClick={() => open('fuel')}>+ Log Fuel</button></div><Table headers={['Vehicle','Date','Liters','Cost']}>{fuel.map((item) => <tr key={item.id} className="border-b border-base-border/60 last:border-0"><Cell>{item.vehicleRegNo}</Cell><Cell>{formatDate(item.logDate)}</Cell><Cell>{Number(item.liters).toFixed(2)} L</Cell><Cell>{money(item.cost)}</Cell></tr>)}</Table></section>
    <section className="panel mt-6 overflow-x-auto p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white">Other Expenses (Toll / Misc)</h2><button className="btn-primary" onClick={() => open('expense')}>+ Add Expense</button></div><Table headers={['Trip','Vehicle','Toll','Other','Maint.','Total','Status']}>{expenses.map((item) => <tr key={item.id} className="border-b border-base-border/60 last:border-0"><Cell>{item.tripId ? `#${item.tripId}` : '—'}</Cell><Cell>{item.vehicleRegNo}</Cell><Cell>{money(item.toll)}</Cell><Cell>{money(item.other)}</Cell><Cell>{item.maintenanceService || '—'}</Cell><Cell>{money(item.total)}</Cell><Cell>{item.tripStatus ? <StatusBadge status={item.tripStatus} /> : <span className="text-gray-500">Unlinked</span>}</Cell></tr>)}</Table></section>
    <div className="mt-6 rounded-lg border border-accent/40 bg-accent/10 p-6"><p className="text-sm text-gray-300">Total Operational Cost (Auto) = Fuel + Maint.</p><p className="mt-2 text-3xl font-semibold text-accent">{money(summary.totalOperationalCost)}</p></div>
    {modal && <Modal title={modal === 'fuel' ? 'Log Fuel' : 'Add Expense'} close={() => setModal('')}><form onSubmit={save} className="space-y-4">{modal === 'fuel' ? <><Select label="Vehicle" value={form.vehicleId} onChange={setField('vehicleId')} error={errors.vehicleId} options={options.vehicles} /><Input label="Date" type="date" max={today} value={form.logDate} onChange={setField('logDate')} error={errors.logDate} /><Input label="Liters" type="number" min="0" value={form.liters} onChange={setField('liters')} error={errors.liters} /><Input label="Cost (₹)" type="number" min="0" value={form.cost} onChange={setField('cost')} error={errors.cost} /></> : <><Select label="Vehicle" value={form.vehicleId} onChange={setField('vehicleId')} error={errors.vehicleId} options={options.vehicles} /><Select label="Trip (optional)" value={form.tripId} onChange={setField('tripId')} options={options.trips.map((t) => ({ id: t.id, regNo: `#${t.id} · ${t.source} → ${t.destination}` }))} optional /><Select label="Maintenance record (optional)" value={form.maintenanceId} onChange={setField('maintenanceId')} options={options.maintenance.map((m) => ({ id: m.id, regNo: `${m.vehicleRegNo} · ${m.serviceType}` }))} optional /><Input label="Toll (₹)" type="number" min="0" value={form.toll} onChange={setField('toll')} error={errors.cost} /><Input label="Other (₹)" type="number" min="0" value={form.other} onChange={setField('other')} /></>}<button className="btn-primary w-full">Save</button></form></Modal>}
  </div>;
}
function Table({ headers, children }) { return <table className="mt-4 w-full min-w-[640px] text-left text-sm"><thead><tr className="border-b border-base-border text-xs uppercase tracking-wide text-gray-500">{headers.map((h) => <th key={h} className="pb-3 pr-4">{h}</th>)}</tr></thead><tbody>{children}</tbody></table>; }
function Cell({ children }) { return <td className="py-3 pr-4 text-gray-300">{children}</td>; }
function Input({ label, error, ...props }) { return <label className="block text-xs font-medium text-gray-400">{label}<input className="input-field mt-1 w-full" {...props}/>{error && <span className="mt-1 block text-xs text-status-red">{error}</span>}</label>; }
function Select({ label, options, error, optional, ...props }) { return <label className="block text-xs font-medium text-gray-400">{label}<select className="input-field mt-1 w-full" {...props}><option value="">{optional ? 'None' : 'Select vehicle...'}</option>{options.map((item) => <option key={item.id} value={item.id}>{item.regNo}</option>)}</select>{error && <span className="mt-1 block text-xs text-status-red">{error}</span>}</label>; }
function Modal({ title, close, children }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="panel w-full max-w-md p-6"><div className="flex justify-between"><h2 className="text-lg font-semibold text-white">{title}</h2><button className="text-gray-400 hover:text-white" onClick={close}>✕</button></div><div className="mt-5">{children}</div></div></div>; }
function formatDate(value) { return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`)); }
function money(value) { return `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`; }
